ENV['AWS_ACCESS_KEY_ID'] = 'AKIAIQNJO3W5FBIGN6YA'
ENV['AWS_SECRET_ACCESS_KEY'] = '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'
ENV['FOG_DIRECTORY'] = 'lasscheeu'
ENV['FOG_REGION'] = 'eu-west-1'


ENV['MAILCHIMP_API_TOKEN'] = '70e9965e2ed65810dfee57c6e75a6af4-us3'
ENV['MAILCHIMP_LIST_ID'] = '4a3e5ae269'

ENV['MANDRILL_USER_NAME'] = 'info@lassche-lassche.nl'
ENV['MANDRILL_API_KEY'] = 'THYZ-jj4BMpqZBEr8DJmvQ'
